# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: workety 2.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "workety"
  s.version = "2.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Stanislav Senotrusov"]
  s.date = "2017-04-23"
  s.email = "stan@senotrusov.com"
  s.executables = ["workety"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "CONTRIBUTING.md",
    "ISSUE_TEMPLATE.md",
    "LICENSE",
    "PULL_REQUEST_TEMPLATE.md",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/workety",
    "lib/workety.rb",
    "lib/workety/extensions/exception.rb",
    "lib/workety/extensions/exceptional.rb",
    "lib/workety/extensions/kernel.rb",
    "lib/workety/extensions/process.rb",
    "lib/workety/extensions/signal.rb",
    "lib/workety/extensions/socket.rb",
    "lib/workety/extensions/thread.rb",
    "lib/workety/test/graceful_stop_thread.rb",
    "lib/workety/test/simple_thread.rb",
    "lib/workety/test/test_thread.rb",
    "lib/workety/timed_exit.rb",
    "lib/workety/workety.rb",
    "test/exception_tracker.rb",
    "test/logger_init.rb",
    "test/mem_and_load_path.rb",
    "test/new_thread_on_signal.rb",
    "test/server_socket_close.rb",
    "test/server_socket_shutdown.rb",
    "test/signal_handler_exception.rb",
    "test/stdin_eof.rb",
    "workety.gemspec"
  ]
  s.homepage = "https://github.com/senotrusov/workety"
  s.licenses = ["Apache-2.0"]
  s.rubygems_version = "2.5.1"
  s.summary = "Run Ruby/Rails code as a worker: detach, signals, watchdog, threads, reporting"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<trollop>, [">= 0"])
    else
      s.add_dependency(%q<trollop>, [">= 0"])
    end
  else
    s.add_dependency(%q<trollop>, [">= 0"])
  end
end

